In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r"D:/PPBI PROJECT/Data/Procceed/clean_victims_data.csv")
df2 = pd.read_csv(r"D:/PPBI PROJECT/Data/Procceed/cleaned_Arrest_crime_against_women.csv")
df3 = pd.read_csv(r"D:/PPBI PROJECT/Data/Procceed/cleaned_crime_against_women.csv")
df4 = pd.read_csv(r"D:/PPBI PROJECT/Data/Procceed/kidnapping_data.csv")

In [3]:
df1.head(5)

,State,Year,Sub_Group,Cases_Reported,Victims_Above_50_Yrs,Victims_Between_10-14_Yrs,Victims_Between_14-18_Yrs,Victims_Between_18-30_Yrs,Victims_Between_30-50_Yrs,Total_Victims,Victims_Upto_10_Yrs
0,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,0
1,Andaman & Nicobar Islands,2001,Victims of Incest Rape,1,0,0,1,0,0,1,0
2,Andaman & Nicobar Islands,2001,Victims of Other Rape,2,0,0,2,0,0,2,0
3,Andaman & Nicobar Islands,2002,Total Rape Victims,2,0,0,1,1,0,2,0
4,Andaman & Nicobar Islands,2002,Victims of Incest Rape,0,0,0,0,0,0,0,0

In [4]:
df2.head(5)

,State,Year,Group_Name,Sub_Group,Acquitted,Withdrawn,Arrested,Chargesheeted,Convicted,Released_Before_Trial,Trial_Completed,Persons_Under_Trial_At_Year_Beginning,Total_Persons_Under_Trial,High_Crime_Area
0,Andaman & Nicobar Islands,2001,Rape,01. Rape,6,0,3,3,0,0,6,48,51,False
1,Andhra Pradesh,2001,Rape,01. Rape,1168,13,1150,1021,246,34,1414,2597,3618,True
2,Arunachal Pradesh,2001,Rape,01. Rape,1,0,51,31,2,15,3,319,350,True
3,Assam,2001,Rape,01. Rape,403,14,928,585,120,190,523,2283,2868,True
4,Bihar,2001,Rape,01. Rape,756,0,1400,1302,217,241,973,5634,6936,True

In [5]:
df3.head(5)

,State,Year,Group_Name,Sub_Group_Name,Cases_Acquitted,Cases_Chargesheeted,Cases_Convicted,Pending_Investigation_End,Pending_Trial_End,Cases_Reported,Cases_Sent_for_Trial,Trials_Completed,Total_Cases_for_Trial
0,Andaman & Nicobar Islands,2001,Rape,01. Rape,5,3,0,1,34,3,3,5,39
1,Andhra Pradesh,2001,Rape,01. Rape,731,769,197,393,1974,871,769,928,2937
2,Arunachal Pradesh,2001,Rape,01. Rape,1,25,2,18,282,33,25,3,285
3,Assam,2001,Rape,01. Rape,334,495,101,1045,1964,817,495,435,2409
4,Bihar,2001,Rape,01. Rape,406,685,155,488,3185,888,685,561,3746

In [6]:
df4.head(5)

,State,Year,Group_Name,Subgroup_Name,Cases_Reported,Female_Total,Total_Cases,Male_Total,Gender_Gap
0,Andhra Pradesh,2001,Kidnap - For Adoption,01. For Adoption,8,5,8,3,2
1,Arunachal Pradesh,2001,Kidnap - For Adoption,01. For Adoption,0,0,0,0,0
2,Assam,2001,Kidnap - For Adoption,01. For Adoption,0,0,0,0,0
3,Bihar,2001,Kidnap - For Adoption,01. For Adoption,18,0,18,18,-18
4,Chandigarh,2001,Kidnap - For Adoption,01. For Adoption,0,0,0,0,0

In [7]:
merged_df = pd.merge(
    df1,df2,
    on = ['State','Year'],
    how = 'inner'
)
print(merged_df.head())

                       State  Year         Sub_Group_x  Cases_Reported  \
0  Andaman & Nicobar Islands  2001  Total Rape Victims               3
1  Andaman & Nicobar Islands  2001  Total Rape Victims               3
2  Andaman & Nicobar Islands  2001  Total Rape Victims               3
3  Andaman & Nicobar Islands  2001  Total Rape Victims               3
4  Andaman & Nicobar Islands  2001  Total Rape Victims               3

   Victims_Above_50_Yrs  Victims_Between_10-14_Yrs  Victims_Between_14-18_Yrs  \
0                     0                          0                          3
1                     0                          0                          3
2                     0                          0                          3
3                     0                          0                          3
4                     0                          0                          3

   Victims_Between_18-30_Yrs  Victims_Between_30-50_Yrs  Total_Victims  ...  \
0                          0                          0              3  ...
1                          0                          0              3  ...
2                          0                          0              3  ...
3                          0                          0              3  ...
4                          0                          0              3  ...

   Acquitted Withdrawn Arrested  Chargesheeted  Convicted  \
0          6         0        3              3          0
1          2         0        4              5          0
2          0         0        0              0          0
3          2         0       19             27          0
4          0         0        1              1          0

   Released_Before_Trial  Trial_Completed  \
0                      0                6
1                      0                2
2                      0                0
3                      0                2
4                      0                0

   Persons_Under_Trial_At_Year_Beginning  Total_Persons_Under_Trial  \
0                                     48                         51
1                                     22                         27
2                                      1                          1
3                                     72                         99
4                                      5                          6

   High_Crime_Area
0            False
1            False
2            False
3             True
4            False

[5 rows x 23 columns]

In [8]:
merged_df.head(5)

,State,Year,Sub_Group_x,Cases_Reported,Victims_Above_50_Yrs,Victims_Between_10-14_Yrs,Victims_Between_14-18_Yrs,Victims_Between_18-30_Yrs,Victims_Between_30-50_Yrs,Total_Victims,...,Acquitted,Withdrawn,Arrested,Chargesheeted,Convicted,Released_Before_Trial,Trial_Completed,Persons_Under_Trial_At_Year_Beginning,Total_Persons_Under_Trial,High_Crime_Area
0,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,...,6,0,3,3,0,0,6,48,51,False
1,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,...,2,0,4,5,0,0,2,22,27,False
2,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,...,0,0,0,0,0,0,0,1,1,False
3,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,...,2,0,19,27,0,0,2,72,99,True
4,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,...,0,0,1,1,0,0,0,5,6,False

In [9]:
print(merged_df.isnull().sum())

State                                    0
Year                                     0
Sub_Group_x                              0
Cases_Reported                           0
Victims_Above_50_Yrs                     0
Victims_Between_10-14_Yrs                0
Victims_Between_14-18_Yrs                0
Victims_Between_18-30_Yrs                0
Victims_Between_30-50_Yrs                0
Total_Victims                            0
Victims_Upto_10_Yrs                      0
Group_Name                               0
Sub_Group_y                              0
Acquitted                                0
Withdrawn                                0
Arrested                                 0
Chargesheeted                            0
Convicted                                0
Released_Before_Trial                    0
Trial_Completed                          0
Persons_Under_Trial_At_Year_Beginning    0
Total_Persons_Under_Trial                0
High_Crime_Area                          0
dtype: int64

In [10]:
merged_df.duplicated().sum()

np.int64(0)

In [11]:
merged_df.describe()

,Year,Cases_Reported,Victims_Above_50_Yrs,Victims_Between_10-14_Yrs,Victims_Between_14-18_Yrs,Victims_Between_18-30_Yrs,Victims_Between_30-50_Yrs,Total_Victims,Victims_Upto_10_Yrs,Acquitted,Withdrawn,Arrested,Chargesheeted,Convicted,Released_Before_Trial,Trial_Completed,Persons_Under_Trial_At_Year_Beginning,Total_Persons_Under_Trial
count,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000,12495.000000
mean,2005.478992,361.525250,1.860584,23.642897,52.972229,212.757903,60.168707,361.802801,10.400480,1257.048499,126.871309,1245.567107,1209.839376,274.527491,201.059064,823.381273,4259.468187,5510.963505
std,2.875244,591.349361,4.630281,50.684184,114.810127,349.688822,118.152506,591.586112,19.503633,2015.620986,534.404030,4239.952426,3941.840912,1120.212983,914.530816,2812.183255,16512.389971,20132.305098
min,2001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2003.000000,4.000000,0.000000,0.000000,0.000000,1.000000,0.000000,4.000000,0.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2005.000000,37.000000,0.000000,3.000000,5.000000,15.000000,4.000000,37.000000,2.000000,662.000000,0.000000,6.000000,22.000000,5.000000,1.000000,4.000000,47.000000,90.000000
75%,2008.000000,529.000000,1.000000,19.000000,42.000000,308.000000,59.000000,532.000000,11.000000,1961.000000,17.000000,503.000000,602.000000,121.000000,32.000000,352.000000,1345.000000,2156.000000
max,2010.000000,3135.000000,43.000000,416.000000,826.000000,1835.000000,811.000000,3136.000000,131.000000,24476.000000,8541.000000,63332.000000,47745.000000,27706.000000,16058.000000,48532.000000,266808.000000,306044.000000

In [12]:
(merged_df['Sub_Group_x'] == merged_df['Sub_Group_y']).sum()

np.int64(0)

In [13]:
(merged_df['Sub_Group_x'] == merged_df['Sub_Group_y']).all()

np.False_

In [14]:
merged_df[['Sub_Group_x','Sub_Group_y']].isnull().sum()

Sub_Group_x    0
Sub_Group_y    0
dtype: int64

In [15]:
merged_df[
    merged_df['Sub_Group_x'].isna() |
    merged_df['Sub_Group_y'].isna()
][['Sub_Group_x','Sub_Group_y']].head()

Empty DataFrame
Columns: [Sub_Group_x, Sub_Group_y]
Index: []

In [16]:
merged_df['Sub_Group_x'].fillna('Missing').equals(
    merged_df['Sub_Group_y'].fillna('Missing')
)

False

In [17]:
print(merged_df['Sub_Group_x'].nunique())
print(merged_df['Sub_Group_y'].nunique())

3
12

In [18]:
df1.columns

Index(['State', 'Year', 'Sub_Group', 'Cases_Reported', 'Victims_Above_50_Yrs',
       'Victims_Between_10-14_Yrs', 'Victims_Between_14-18_Yrs',
       'Victims_Between_18-30_Yrs', 'Victims_Between_30-50_Yrs',
       'Total_Victims', 'Victims_Upto_10_Yrs'],
      dtype='str')

In [19]:
df2.columns

Index(['State', 'Year', 'Group_Name', 'Sub_Group', 'Acquitted', 'Withdrawn',
       'Arrested', 'Chargesheeted', 'Convicted', 'Released_Before_Trial',
       'Trial_Completed', 'Persons_Under_Trial_At_Year_Beginning',
       'Total_Persons_Under_Trial', 'High_Crime_Area'],
      dtype='str')

In [20]:
df1.shape

(1050, 11)

In [21]:
merged_df.shape

(12495, 23)

In [22]:
df2.shape

(4165, 14)

In [23]:
df1[['State','Year']].duplicated().sum()

np.int64(700)

In [24]:
df2[['State','Year']].duplicated().sum()

np.int64(3815)

In [25]:
df1.to_csv("d1 and d2_data.csv", index=False)

In [26]:
merged_df2 = pd.merge(
    df3,df4,
    on = ['State','Year'],
    how = 'inner'
)
print(merged_df.head())

                       State  Year         Sub_Group_x  Cases_Reported  \
0  Andaman & Nicobar Islands  2001  Total Rape Victims               3
1  Andaman & Nicobar Islands  2001  Total Rape Victims               3
2  Andaman & Nicobar Islands  2001  Total Rape Victims               3
3  Andaman & Nicobar Islands  2001  Total Rape Victims               3
4  Andaman & Nicobar Islands  2001  Total Rape Victims               3

   Victims_Above_50_Yrs  Victims_Between_10-14_Yrs  Victims_Between_14-18_Yrs  \
0                     0                          0                          3
1                     0                          0                          3
2                     0                          0                          3
3                     0                          0                          3
4                     0                          0                          3

   Victims_Between_18-30_Yrs  Victims_Between_30-50_Yrs  Total_Victims  ...  \
0                          0                          0              3  ...
1                          0                          0              3  ...
2                          0                          0              3  ...
3                          0                          0              3  ...
4                          0                          0              3  ...

   Acquitted Withdrawn Arrested  Chargesheeted  Convicted  \
0          6         0        3              3          0
1          2         0        4              5          0
2          0         0        0              0          0
3          2         0       19             27          0
4          0         0        1              1          0

   Released_Before_Trial  Trial_Completed  \
0                      0                6
1                      0                2
2                      0                0
3                      0                2
4                      0                0

   Persons_Under_Trial_At_Year_Beginning  Total_Persons_Under_Trial  \
0                                     48                         51
1                                     22                         27
2                                      1                          1
3                                     72                         99
4                                      5                          6

   High_Crime_Area
0            False
1            False
2            False
3             True
4            False

[5 rows x 23 columns]

In [27]:
merged_df2

,State,Year,Group_Name_x,Sub_Group_Name,Cases_Acquitted,Cases_Chargesheeted,Cases_Convicted,Pending_Investigation_End,Pending_Trial_End,Cases_Reported_x,Cases_Sent_for_Trial,Trials_Completed,Total_Cases_for_Trial,Group_Name_y,Subgroup_Name,Cases_Reported_y,Female_Total,Total_Cases,Male_Total,Gender_Gap
0,Andhra Pradesh,2001,Rape,01. Rape,731,769,197,393,1974,871,769,928,2937,Kidnap - For Adoption,01. For Adoption,8,5,8,3,2
1,Andhra Pradesh,2001,Rape,01. Rape,731,769,197,393,1974,871,769,928,2937,Kidnap - For Begging,02. For Begging,2,0,2,2,-2
2,Andhra Pradesh,2001,Rape,01. Rape,731,769,197,393,1974,871,769,928,2937,Kidnap - For Camel Racing,03. for Camel Racing,0,0,0,0,0
3,Andhra Pradesh,2001,Rape,01. Rape,731,769,197,393,1974,871,769,928,2937,Kidnap - For Illicit Intercourse,04. For Illicit Intercourse,78,78,78,0,78
4,Andhra Pradesh,2001,Rape,01. Rape,731,769,197,393,1974,871,769,928,2937,Kidnap - For Marriage,05. For Marriage,339,332,339,7,325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38093,West Bengal,2010,Total Crime Against Women,12. Total Crimes Against Women,4084,23528,435,17892,113793,26125,23528,4519,118437,Kidnap - For Selling Bodyparts,10. For Selling Bodyparts,0,0,0,0,0
38094,West Bengal,2010,Total Crime Against Women,12. Total Crimes Against Women,4084,23528,435,17892,113793,26125,23528,4519,118437,Kidnap - For Slavery,11. For Slavery,6,1,6,5,-4
38095,West Bengal,2010,Total Crime Against Women,12. Total Crimes Against Women,4084,23528,435,17892,113793,26125,23528,4519,118437,Kidnap - For Unlawful Activity,12. For Unlawful Activity,155,91,169,78,13
38096,West Bengal,2010,Total Crime Against Women,12. Total Crimes Against Women,4084,23528,435,17892,113793,26125,23528,4519,118437,Kidnap - For Other Purposes,13. Other Purposes,2271,1885,2271,386,1499
38097,West Bengal,2010,Total Crime Against Women,12. Total Crimes Against Women,4084,23528,435,17892,113793,26125,23528,4519,118437,Kidnap - Total,14. Total (Sum of 1-13 Above),3345,2786,3391,605,2181

In [29]:
merged_df.isnull().sum()

State                                    0
Year                                     0
Sub_Group_x                              0
Cases_Reported                           0
Victims_Above_50_Yrs                     0
Victims_Between_10-14_Yrs                0
Victims_Between_14-18_Yrs                0
Victims_Between_18-30_Yrs                0
Victims_Between_30-50_Yrs                0
Total_Victims                            0
Victims_Upto_10_Yrs                      0
Group_Name                               0
Sub_Group_y                              0
Acquitted                                0
Withdrawn                                0
Arrested                                 0
Chargesheeted                            0
Convicted                                0
Released_Before_Trial                    0
Trial_Completed                          0
Persons_Under_Trial_At_Year_Beginning    0
Total_Persons_Under_Trial                0
High_Crime_Area                          0
dtype: int64

In [30]:
merged_df.duplicated().sum()

np.int64(0)