In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:/PPBI PROJECT/Data/Raw/Victims_of_rape.csv")

In [3]:
df

,Area_Name,Year,Subgroup,Rape_Cases_Reported,Victims_Above_50_Yrs,Victims_Between_10-14_Yrs,Victims_Between_14-18_Yrs,Victims_Between_18-30_Yrs,Victims_Between_30-50_Yrs,Victims_of_Rape_Total,Victims_Upto_10_Yrs
0,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,0
1,Andaman & Nicobar Islands,2001,Victims of Incest Rape,1,0,0,1,0,0,1,0
2,Andaman & Nicobar Islands,2001,Victims of Other Rape,2,0,0,2,0,0,2,0
3,Andaman & Nicobar Islands,2002,Total Rape Victims,2,0,0,1,1,0,2,0
4,Andaman & Nicobar Islands,2002,Victims of Incest Rape,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1045,West Bengal,2009,Victims of Incest Rape,3,0,0,1,1,1,3,0
1046,West Bengal,2009,Victims of Other Rape,2333,0,18,84,1834,391,2333,6
1047,West Bengal,2010,Total Rape Victims,2311,0,22,51,1779,459,2311,0
1048,West Bengal,2010,Victims of Incest Rape,4,0,1,0,2,1,4,0
1049,West Bengal,2010,Victims of Other Rape,2307,0,21,51,1777,458,2307,0

In [4]:
df.head()

,Area_Name,Year,Subgroup,Rape_Cases_Reported,Victims_Above_50_Yrs,Victims_Between_10-14_Yrs,Victims_Between_14-18_Yrs,Victims_Between_18-30_Yrs,Victims_Between_30-50_Yrs,Victims_of_Rape_Total,Victims_Upto_10_Yrs
0,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,0
1,Andaman & Nicobar Islands,2001,Victims of Incest Rape,1,0,0,1,0,0,1,0
2,Andaman & Nicobar Islands,2001,Victims of Other Rape,2,0,0,2,0,0,2,0
3,Andaman & Nicobar Islands,2002,Total Rape Victims,2,0,0,1,1,0,2,0
4,Andaman & Nicobar Islands,2002,Victims of Incest Rape,0,0,0,0,0,0,0,0

In [5]:
df.shape
#check how many and columns in the data

(1050, 11)

In [6]:
df.info()
#check data types

<class 'pandas.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Area_Name                  1050 non-null   str
 1   Year                       1050 non-null   int64
 2   Subgroup                   1050 non-null   str
 3   Rape_Cases_Reported        1050 non-null   int64
 4   Victims_Above_50_Yrs       1050 non-null   int64
 5   Victims_Between_10-14_Yrs  1050 non-null   int64
 6   Victims_Between_14-18_Yrs  1050 non-null   int64
 7   Victims_Between_18-30_Yrs  1050 non-null   int64
 8   Victims_Between_30-50_Yrs  1050 non-null   int64
 9   Victims_of_Rape_Total      1050 non-null   int64
 10  Victims_Upto_10_Yrs        1050 non-null   int64
dtypes: int64(9), str(2)
memory usage: 90.4 KB

In [7]:
df.isnull().sum()
#check null values

Area_Name                    0
Year                         0
Subgroup                     0
Rape_Cases_Reported          0
Victims_Above_50_Yrs         0
Victims_Between_10-14_Yrs    0
Victims_Between_14-18_Yrs    0
Victims_Between_18-30_Yrs    0
Victims_Between_30-50_Yrs    0
Victims_of_Rape_Total        0
Victims_Upto_10_Yrs          0
dtype: int64

In [8]:
df.duplicated().sum()
#count duplicates rows

np.int64(0)

In [9]:
df.columns =df.columns.str.strip()
#removing extra spaces

In [10]:
df= df.rename(columns = {
    'Area_Name' :'State',
    'Sub_group' : 'Sub_Group',
    'Rape_Cases_Reported' : 'Cases_Reported',
    'Victims_of_Rape_Total' : 'Total_Victims'
})

In [11]:
df['Sub_Group'].unique()
#find cateogries

KeyError: 'Sub_Group'

In [ ]:
df['Victim_Percentage'] = (
    df['Total_Victims'] /
    df['Total_Victims'].sum()
) * 100

In [ ]:
State_Data = df.groupby('State') ['Total_Victims'].sum()
#state by grouping of victims
#Identify the top crime state

In [ ]:
Year_Data = df.groupby('Year') ['Total_Victims'].sum()
#Crime Trend analysis

In [ ]:
df.dtypes

State                            str
Year                           int64
Sub_Group                        str
Cases_Reported                 int64
Victims_Above_50_Yrs           int64
Victims_Between_10-14_Yrs      int64
Victims_Between_14-18_Yrs      int64
Victims_Between_18-30_Yrs      int64
Victims_Between_30-50_Yrs      int64
Total_Victims                  int64
Victims_Upto_10_Yrs            int64
Victim_Percentage            float64
dtype: object

In [ ]:
df['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010])

In [ ]:
df.columns

Index(['State', 'Year', 'Sub_Group', 'Cases_Reported', 'Victims_Above_50_Yrs',
       'Victims_Between_10-14_Yrs', 'Victims_Between_14-18_Yrs',
       'Victims_Between_18-30_Yrs', 'Victims_Between_30-50_Yrs',
       'Total_Victims', 'Victims_Upto_10_Yrs', 'Victim_Percentage'],
      dtype='str')

In [ ]:
(
    df['Victims_Upto_10_Yrs'] +
    df['Victims_Between_10-14_Yrs'] +
    df['Victims_Between_14-18_Yrs'] +
    df['Victims_Between_18-30_Yrs'] +
    df['Victims_Between_30-50_Yrs'] +
    df['Victims_Above_50_Yrs']
).equals(df['Total_Victims'])

True

In [ ]:
df.describe()

,Year,Cases_Reported,Victims_Above_50_Yrs,Victims_Between_10-14_Yrs,Victims_Between_14-18_Yrs,Victims_Between_18-30_Yrs,Victims_Between_30-50_Yrs,Total_Victims,Victims_Upto_10_Yrs
count,1050.00000,1050.000000,1050.000000,1050.000000,1050.000000,1050.000000,1050.000000,1050.000000,1050.000000
mean,2005.50000,361.920000,1.866667,23.657143,53.085714,212.937143,60.236190,362.198095,10.415238
std,2.87365,592.180572,4.640286,50.677418,115.127899,350.135760,118.322713,592.418089,19.533134
min,2001.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2003.00000,4.000000,0.000000,0.000000,0.000000,1.000000,0.000000,4.000000,0.000000
50%,2005.50000,37.000000,0.000000,3.000000,5.000000,15.500000,4.000000,37.000000,2.000000
75%,2008.00000,527.500000,1.000000,19.000000,42.000000,308.000000,58.750000,531.500000,11.000000
max,2010.00000,3135.000000,43.000000,416.000000,826.000000,1835.000000,811.000000,3136.000000,131.000000

In [ ]:
df.to_csv("clean_victims_data.csv", index=False)

In [ ]:
df

,State,Year,Subgroup,Cases_Reported,Victims_Above_50_Yrs,Victims_Between_10-14_Yrs,Victims_Between_14-18_Yrs,Victims_Between_18-30_Yrs,Victims_Between_30-50_Yrs,Total_Victims,Victims_Upto_10_Yrs
0,Andaman & Nicobar Islands,2001,Total Rape Victims,3,0,0,3,0,0,3,0
1,Andaman & Nicobar Islands,2001,Victims of Incest Rape,1,0,0,1,0,0,1,0
2,Andaman & Nicobar Islands,2001,Victims of Other Rape,2,0,0,2,0,0,2,0
3,Andaman & Nicobar Islands,2002,Total Rape Victims,2,0,0,1,1,0,2,0
4,Andaman & Nicobar Islands,2002,Victims of Incest Rape,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1045,West Bengal,2009,Victims of Incest Rape,3,0,0,1,1,1,3,0
1046,West Bengal,2009,Victims of Other Rape,2333,0,18,84,1834,391,2333,6
1047,West Bengal,2010,Total Rape Victims,2311,0,22,51,1779,459,2311,0
1048,West Bengal,2010,Victims of Incest Rape,4,0,1,0,2,1,4,0
1049,West Bengal,2010,Victims of Other Rape,2307,0,21,51,1777,458,2307,0